### ISSUE TITLE
zk: node does not exist

### ISSUE THREAD

**Issue by ethicalmohit** [DataDog/kafka-kit#246]
I am getting below error while trying to rebalance one topic. The node is healthy but it says that node doesn't exist.

Command: 
```
./go/bin/topicmappr rebalance --brokers 0,1 --zk-addr "kafka-0.domain.com:2181" --topics topicname
Error fetching metrics metadata: [/topicmappr/partitionmeta] zk: node does not exist

```
Zookeeper Health

```
[root@ip-10-0-63-55 ~]# echo mntr | nc kafka-0.domain.com 2181
zk_version	3.4.10-39d3a4f269333c922ed3db283be479f9deacaa0f, built on 03/23/2017 10:13 GMT
zk_avg_latency	0
zk_max_latency	17
zk_min_latency	0
zk_packets_received	27346
zk_packets_sent	27359
zk_num_alive_connections	3
zk_outstanding_requests	0
zk_server_state	follower
zk_znode_count	180
zk_watch_count	25
zk_ephemerals_count	4
zk_approximate_data_size	13762
zk_open_file_descriptor_count	119
zk_max_file_descriptor_count	1048576
```

**Comment by davidrusu** [comment]
The error seems to be saying that the data node `/topicmappr/partitionmeta` in Zookeeper is missing (it's not saying that the zookeeper server is down)

**Comment by jamiealquiza** [comment]
I'll make this error more informative, but this means that there's no metrics data available to perform the rebalance (since it needs additive visibility data that's not otherwise exposed in ZK/etc). [Metricsfetcher](https://github.com/DataDog/kafka-kit/tree/master/cmd/metricsfetcher) is a convenience that provides this from Datadog; which if you're not a user, you could script in the metrics from other systems.

**Comment by jrask** [comment]
Spent some time on this before realizing that it does not work if I am not a datadog user. Would be great if this was clear from the docs.

**Comment by jamiealquiza** [comment]
The docs for both the rebalance and rebuild commands mention that metrics data is required in order to make decisions:

- https://github.com/DataDog/kafka-kit/wiki/Rebalance-command#usage-notes
- https://github.com/DataDog/kafka-kit/wiki/Rebuild-command#storage

Both point to the tool [metricsfetcher](https://github.com/DataDog/kafka-kit/tree/master/cmd/metricsfetcher), which _is_ an initial implementation using Datadog, but being a Datadog customer is not a requirement. The required metrics data structure / format is also documented as well and as long as this data is present, from any source (i.e. prometheus, etc), topicmappr storage related operations can be performed.

**Comment by jrask** [comment]
This is from the README, it says **drop-in replacement**. I am only trying to help out here, if you feel that the docs are good enough thats fair.

A drop-in replacement for the kafka-reassign-partition tool bundled with Kafka. Topicmappr allows for minimal movement broker replacements, many-at-once topic management, replica placement constraints, storage-based rebalancing, and other features.

**Comment by jamiealquiza** [comment]
That is true for the 'count' (default) storage placement strategy in the rebuild sub-command. Originally, that's all topicmappr was and all the other features are an extension. You are correct that reading the docs as of today, this can feel misleading. I'll clarify this.
