### ISSUE TITLE
when to use rebalance vs rebuild during scaling up 

### ISSUE THREAD

**Issue by divbok** [DataDog/kafka-kit#344]
I dont see the difference between using rebalance and rebuild while scaling up . I ran on a cluster the above use case .
rebuild didnt suggest me anything even after applying --force-rebuild but rebalance did. We're quite confused on when to use what ? Could you guide us

**Comment by jamiealquiza** [comment]
Have you seen this wiki entry which shows some exmaples? https://github.com/DataDog/kafka-kit/wiki/Topicmappr-Usage-Guide.

Generally:
- `rebuild` is used for replacing or removing brokers. It does have the `--placement storage` option which means when partitions are moved, move them based on side. This can effectively be used for a scale up _if_ you're replacing a few or all the brokers, but it probably isn't what you want.
- `rebalance` is used when you want to better redistribute storage utilization among a set of brokers. This can optionally include _new_ brokers, effectively making it a scale up operation. One difference between `rebalance` and `rebuild` is that `rebalance` does not allow you to remove brokers. 

I recently added another subcommand, `scale`, which is a wrapper for `rebalance` but its default parameters make more sense for scaling (scaling meaning you have topics on brokers 1,2,3 and want to add 4,5; evenly draw partitions from 1,2,3 to place on 4,5 so that utilization is roughly equal across all brokers). I still need to document this in the wiki.

As a recap:
- Use rebuild when you want to remove or replace brokers.
- Use rebalance when you want to redistribute data among a set of brokers.
- Use scale when you want to introduce additional brokers and redistribute data.

**Comment by divbok** [comment]
Thanks for the info. This helps in resolving the confusion.
